//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.App.WCF.Security {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.Security.IIdentificacao")]
    public interface IIdentificacao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentificacao/Login", ReplyAction="http://tempuri.org/IIdentificacao/LoginResponse")]
        Lab.Models.Identificacao Login(Lab.Models.ProfessorCredencial professorCredencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentificacao/Login", ReplyAction="http://tempuri.org/IIdentificacao/LoginResponse")]
        System.Threading.Tasks.Task<Lab.Models.Identificacao> LoginAsync(Lab.Models.ProfessorCredencial professorCredencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentificacao/Logout", ReplyAction="http://tempuri.org/IIdentificacao/LogoutResponse")]
        bool Logout(Lab.Models.Identificacao identificacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIdentificacao/Logout", ReplyAction="http://tempuri.org/IIdentificacao/LogoutResponse")]
        System.Threading.Tasks.Task<bool> LogoutAsync(Lab.Models.Identificacao identificacao);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIdentificacaoChannel : Lab.App.WCF.Security.IIdentificacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IdentificacaoClient : System.ServiceModel.ClientBase<Lab.App.WCF.Security.IIdentificacao>, Lab.App.WCF.Security.IIdentificacao {
        
        public IdentificacaoClient() {
        }
        
        public IdentificacaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IdentificacaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdentificacaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdentificacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Lab.Models.Identificacao Login(Lab.Models.ProfessorCredencial professorCredencial) {
            return base.Channel.Login(professorCredencial);
        }
        
        public System.Threading.Tasks.Task<Lab.Models.Identificacao> LoginAsync(Lab.Models.ProfessorCredencial professorCredencial) {
            return base.Channel.LoginAsync(professorCredencial);
        }
        
        public bool Logout(Lab.Models.Identificacao identificacao) {
            return base.Channel.Logout(identificacao);
        }
        
        public System.Threading.Tasks.Task<bool> LogoutAsync(Lab.Models.Identificacao identificacao) {
            return base.Channel.LogoutAsync(identificacao);
        }
    }
}
