//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.Service.DataDriven
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int Id { get; set; }
        public int AlunoId { get; set; }
        public int ProfessorId { get; set; }
        public int TurmaId { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
